server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/v1/tickets/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/v1/events/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
